name: engine_app
description: "Engine App with Assets & Metadata Module"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/metadata.json
    - assets/splash/splash_logo.png
    - assets/scripts/bootstrap.lua
    - assets/scripts/patcher.lua
    - assets/database/app_storage.db
    - assets/textures/character_diffuse.astc
    - assets/audio/bgm_theme.ogg
    - assets/video/intro_cinematic.mp4

  fonts:
    - family: EngineFont
      fonts:
        - asset: assets/fonts/engine_font.ttf
